### ISSUE TITLE
Can't find breakfast folder

### ISSUE THREAD

**Issue by alyssamzhu** [IntroToCode/Spring21_Recipes_Codemates2#12]
## 💬 Discussion topic

Breakfast folder is missing

## ❗ Potential issues

Breakfast folder went missing today (Monday 4/5); it was present yesterday

## 👥 People to consult

@joewadcan do you see the breakfast folder at all? We can't seem to find it and we're not sure if we deleted it by accident or how we might be able to tell what happened to it.

## 📃 Details

Text

**Comment by lindalee117** [comment]
repasted in the file - issue closed!
