### ISSUE TITLE
Review breakfast recipe?

### ISSUE THREAD

**Issue by cristinap37** [IntroToCode/Spring21_Recipes_Codemates2#4]
## 💬 Discussion topic

Can someone make sure that the breakfast recipe is complete in our pull request list?

## ❗ Potential issues

incomplete recipe

## 👥 People to consult

@IntroToCode/fall20_codemates2 
## 📃 Details

Text

**Comment by lindalee117** [comment]
@cristinap37 - Cristina I have adjusted the pull request to include the full breakfast recipe. Therefore, we can close this issue!

**Comment by cristinap37** [comment]
Issue resolved
