### ISSUE TITLE
Write access to merge pull requests?

### ISSUE THREAD

**Issue by cristinap37** [IntroToCode/Spring21_Recipes_Codemates2#5]
## 💬 Discussion topic

Do you guys have write access to merge pull requests? It says that I don't and therefore can't push anything to the main branch. Are others encountering this issue?

## ❗ Potential issues

Text

## 👥 People to consult

Text

## 📃 Details

Text

**Comment by alyssamzhu** [comment]
It doesn't look I have access either and I'm also having trouble with creating pull requests themselves in this particular repository. I will keep digging around to try to figure out what I'm doing wrong!

**Comment by lindalee117** [comment]
Agree with this issue -  I don't have access either.

**Comment by lindalee117** [comment]
@joewadcan - moving your call out to this issue. Thanks for confirming it was an access issue! We would really appreciate just 1 more day to finalize the pull requests - we'll likely finalize by end of day. We will test & see if we have any further issue!

**Comment by lindalee117** [comment]
@cristinap37 once we confirm that we can merge, let's close this issue
