### ISSUE TITLE
Acceptance criteria for review

### ISSUE THREAD

**Issue by alyssamzhu** [IntroToCode/Spring21_Recipes_Codemates2#6]
## 💬 Discussion topic

Criteria for recipes and for approving changes. This will help us decide whether changes to the doc are go/no-go

## ❗ Potential issues
- Could have different criteria for what constitutes an approval
- Timing issues, where one member reviews and approves of a change but another member hasn't seen the change yet

## 👥 People to consult
Team members in Group 2
@cristinap37
@lindalee117

## 📃 Details
Recipes must have...
- Clear objective (name of recipe)
- Clear details (must include a minimum of ingredients and steps to make recipe)
- Reviewed by 1 team member

**Comment by lindalee117** [comment]
@alyssamzhu Thanks for putting this together! This looks good to me. 
 @alchurchy to also comment!

**Comment by cristinap37** [comment]
This looks good too!
